<?php

namespace Amplify\System\Backend\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['id' => '1', 'category_code' => 'Audio', 'category_name' => '{"en":"Audio"}', 'category_slug' => 'audio', 'pim_category_id' => 'a1', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:14:40', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '2', 'category_code' => 'Cameras-camcorders', 'category_name' => '{"en":"Cameras & Camcorders"}', 'category_slug' => 'cameras-camcorders', 'pim_category_id' => 'c6', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '19', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:15:34', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '3', 'category_code' => 'Computers-Tablets', 'category_name' => '{"en":"Computers & Tablets"}', 'category_slug' => 'computers-tablets', 'pim_category_id' => 'cc', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '20', 'rgt' => '55', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:15:57', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '4', 'category_code' => 'Health-Fitness-Beauty', 'category_name' => '{"en":"Health, Fitness & Fitness"}', 'category_slug' => 'health-fitness-beauty', 'pim_category_id' => 'hf', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '66', 'rgt' => '67', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:17:00', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '5', 'category_code' => 'TV-Home-Theater', 'category_name' => '{"en":"TV & Home Theater"}', 'category_slug' => 'tv-home-theater', 'pim_category_id' => 'tv', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '56', 'rgt' => '65', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:19:16', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '6', 'category_code' => 'b1', 'category_name' => '{"en":"Binoculars, Telescopes & Optics"}', 'category_slug' => 'b1', 'pim_category_id' => 'b1', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '2', 'level' => null, 'depth' => '2', 'lft' => '17', 'rgt' => '18', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:20:11', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '7', 'category_code' => 'Camcorder-Acc', 'category_name' => '{"en":"Camcorder Accessories"}', 'category_slug' => 'camcorder-acc', 'pim_category_id' => 'cca', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '2', 'level' => null, 'depth' => '2', 'lft' => '15', 'rgt' => '16', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:21:43', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '8', 'category_code' => 'Camcorders', 'category_name' => '{"en":"Camcorders"}', 'category_slug' => 'camcorders', 'pim_category_id' => 'c99', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '2', 'level' => null, 'depth' => '2', 'lft' => '13', 'rgt' => '14', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:22:40', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '9', 'category_code' => 'Digital-Cam-Acc', 'category_name' => '{"en":"Digital Camera Accessories"}', 'category_slug' => 'digital-cam-acc', 'pim_category_id' => 'dca', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '2', 'level' => null, 'depth' => '2', 'lft' => '11', 'rgt' => '12', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:23:28', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '10', 'category_code' => 'Digital-Cameras', 'category_name' => '{"en":"Digital Cameras"}', 'category_slug' => 'digital-cameras', 'pim_category_id' => 'dc', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '2', 'level' => null, 'depth' => '2', 'lft' => '5', 'rgt' => '10', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:24:05', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '11', 'category_code' => 'dig-slr', 'category_name' => '{"en":"Digital SLR Cameras"}', 'category_slug' => 'dig-slr', 'pim_category_id' => 'dslr', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '10', 'level' => null, 'depth' => '3', 'lft' => '6', 'rgt' => '7', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:25:58', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '12', 'category_code' => 'P-S-Cameras', 'category_name' => '{"en":"Point & Shoot Cameras"}', 'category_slug' => 'p-d-cameras', 'pim_category_id' => 'psc', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '10', 'level' => null, 'depth' => '3', 'lft' => '8', 'rgt' => '9', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:26:45', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '13', 'category_code' => 'comp-acc', 'category_name' => '{"en":"Computer Accessories & Peripherals"}', 'category_slug' => 'comp-acc', 'pim_category_id' => 'c10', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '27', 'rgt' => '36', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:48:15', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '14', 'category_code' => 'comp-cards', 'category_name' => '{"en":"Computer Cards & Components"}', 'category_slug' => 'comp-cards', 'pim_category_id' => 'c11', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '13', 'level' => null, 'depth' => '3', 'lft' => '30', 'rgt' => '31', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:48:47', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '15', 'category_code' => 'Laptops', 'category_name' => '{"en":"Laptops"}', 'category_slug' => 'laptops', 'pim_category_id' => 'c12', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '21', 'rgt' => '26', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:49:10', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '16', 'category_code' => 'Monitors', 'category_name' => '{"en":"Monitors"}', 'category_slug' => 'monitors', 'pim_category_id' => 'c13', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '13', 'level' => null, 'depth' => '3', 'lft' => '32', 'rgt' => '33', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:49:28', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '17', 'category_code' => 'printers', 'category_name' => '{"en":"Printers, Ink & Toner"}', 'category_slug' => 'printers', 'pim_category_id' => 'c14', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '37', 'rgt' => '44', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:49:51', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '18', 'category_code' => 'wifi', 'category_name' => '{"en":"Wi-Fi & Networking"}', 'category_slug' => 'wifi', 'pim_category_id' => 'c15', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '45', 'rgt' => '54', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:50:09', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '19', 'category_code' => 'hard-drives', 'category_name' => '{"en":"Hard Drives & Storage"}', 'category_slug' => 'hard-drives', 'pim_category_id' => 'c16', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '13', 'level' => null, 'depth' => '3', 'lft' => '28', 'rgt' => '29', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:50:45', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '20', 'category_code' => 'memory', 'category_name' => '{"en":"Memory (RAM)"}', 'category_slug' => 'memory', 'pim_category_id' => 'c17', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '13', 'level' => null, 'depth' => '3', 'lft' => '34', 'rgt' => '35', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:51:05', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '21', 'category_code' => 'macbooks', 'category_name' => '{"en":"MacBooks"}', 'category_slug' => 'macbooks', 'pim_category_id' => 'c18', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '15', 'level' => null, 'depth' => '3', 'lft' => '22', 'rgt' => '23', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:51:25', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '22', 'category_code' => 'PC-Laptops', 'category_name' => '{"en":"PC Laptops"}', 'category_slug' => 'pc-laptops', 'pim_category_id' => 'c19', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '15', 'level' => null, 'depth' => '3', 'lft' => '24', 'rgt' => '25', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:51:45', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '23', 'category_code' => 'ink', 'category_name' => '{"en":"Ink & Toner"}', 'category_slug' => 'ink', 'pim_category_id' => 'c20', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '17', 'level' => null, 'depth' => '3', 'lft' => '42', 'rgt' => '43', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:52:13', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '24', 'category_code' => 'Inkjet', 'category_name' => '{"en":"Inkjet Printers"}', 'category_slug' => 'inkjet', 'pim_category_id' => 'c21', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '17', 'level' => null, 'depth' => '3', 'lft' => '40', 'rgt' => '41', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:52:39', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '25', 'category_code' => 'Laser', 'category_name' => '{"en":"Laser Printers"}', 'category_slug' => 'laser', 'pim_category_id' => 'c22', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '17', 'level' => null, 'depth' => '3', 'lft' => '38', 'rgt' => '39', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:53:00', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '26', 'category_code' => 'eth-switch', 'category_name' => '{"en":"Ethernet Switches"}', 'category_slug' => 'eth-switch', 'pim_category_id' => 'c24', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '18', 'level' => null, 'depth' => '3', 'lft' => '50', 'rgt' => '51', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:53:32', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '27', 'category_code' => 'net-cab', 'category_name' => '{"en":"Networking Cables"}', 'category_slug' => 'net-cab', 'pim_category_id' => 'c25', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '18', 'level' => null, 'depth' => '3', 'lft' => '48', 'rgt' => '49', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:53:54', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '28', 'category_code' => 'routers', 'category_name' => '{"en":"Routers"}', 'category_slug' => 'routers', 'pim_category_id' => 'c26', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '18', 'level' => null, 'depth' => '3', 'lft' => '46', 'rgt' => '47', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:54:13', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '29', 'category_code' => 'voip', 'category_name' => '{"en":"Voip"}', 'category_slug' => 'voip', 'pim_category_id' => 'c27', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '18', 'level' => null, 'depth' => '3', 'lft' => '52', 'rgt' => '53', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 15:54:27', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '30', 'category_code' => 'tvs', 'category_name' => '{"en":"TVs"}', 'category_slug' => 'tvs', 'pim_category_id' => 'c28', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '5', 'level' => null, 'depth' => '2', 'lft' => '61', 'rgt' => '62', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 16:04:40', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '31', 'category_code' => 'tv-acc', 'category_name' => '{"en":"TV & Home Theater Accessories"}', 'category_slug' => 'tv-acc', 'pim_category_id' => 'c31', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '5', 'level' => null, 'depth' => '2', 'lft' => '57', 'rgt' => '58', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 16:05:00', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '32', 'category_code' => 'sound-bars', 'category_name' => '{"en":"Sound Bars"}', 'category_slug' => 'sound-bars', 'pim_category_id' => 'c32', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '5', 'level' => null, 'depth' => '2', 'lft' => '59', 'rgt' => '60', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 16:05:19', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
            ['id' => '33', 'category_code' => 'proj-screens', 'category_name' => '{"en":"Projectors & Screens"}', 'category_slug' => 'proj-screens', 'pim_category_id' => 'c34', 'is_top_nav' => '0', 'template' => null, 'image' => null, 'parent_id' => '5', 'level' => null, 'depth' => '2', 'lft' => '63', 'rgt' => '64', 'is_new' => '0', 'is_updated' => '0', 'created_at' => '2021-06-08 16:05:43', 'updated_at' => '2021-11-09 07:02:39', 'deleted_at' => null],
        ];

        Category::insert($categories);
    }
}
