<?php

namespace Amplify\System\Backend\Seeders;

use App\Models\MegaMenu;
use App\Models\MegaMenuProduct;
use App\Models\Menu;
use App\Models\MenuGroup;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        MenuGroup::truncate();
        Menu::truncate();
        MegaMenu::truncate();
        MegaMenuProduct::truncate();

        $menu_groups = [
            ['id' => '1', 'template_id' => '1', 'name' => 'Primary Menu', 'short_code' => 'primary-menu', 'blade_location' => 'menus.index', 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-06-09 20:48:59', 'updated_at' => '2022-06-09 20:48:59'],
            ['id' => '2', 'template_id' => '2', 'name' => 'Secondary menu', 'short_code' => 'secondary-menu', 'blade_location' => 'menus.index', 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-06-10 15:29:10', 'updated_at' => '2022-06-10 15:29:10'],
            ['id' => '3', 'template_id' => '1', 'name' => 'Customer Dashboard Sidebar', 'short_code' => 'customer-dashboard-sidebar', 'blade_location' => null, 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-06-10 15:29:10', 'updated_at' => '2022-06-10 15:29:10'],
            ['id' => '4', 'template_id' => '1', 'name' => 'Mobile Sidebar Menu', 'short_code' => 'mobile-sidebar-menu', 'blade_location' => null, 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-07-29 16:11:17', 'updated_at' => '2022-07-29 16:11:17'],
            ['id' => '5', 'template_id' => '3', 'name' => 'Primary Menu Template-3', 'short_code' => 'primary-menu-template-3', 'blade_location' => 'menus.index', 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-09-01 13:56:44', 'updated_at' => '2022-09-01 13:56:44'],
            ['id' => '6', 'template_id' => '3', 'name' => 'Mobile Sidebar Menu Template-3', 'short_code' => 'mobile-sidebar-menu-template-3', 'blade_location' => null, 'class' => null, 'style' => null, 'active' => '1', 'created_at' => '2022-09-01 13:56:44', 'updated_at' => '2022-09-01 13:56:44'],
        ];

        $menus = [
            ['id' => '1', 'group_id' => '1', 'name' => '{"en":"Home"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => 'http://35.170.233.68/', 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-06-09 00:32:41', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '2', 'group_id' => '1', 'name' => '{"en":"Products"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '13', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'type' => 'default', 'created_at' => '2022-06-09 00:32:41', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '3', 'group_id' => '1', 'name' => '{"en":"Account"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => null, 'url' => '/home', 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '25', 'type' => 'default', 'created_at' => '2022-06-09 00:32:41', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '4', 'group_id' => '1', 'name' => '{"en":"Quick Order"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '17', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '13', 'rgt' => '14', 'type' => 'default', 'created_at' => '2022-06-09 00:32:41', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '5', 'group_id' => '1', 'name' => '{"en":"Account Summary"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => null, 'url' => '/home', 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '15', 'rgt' => '16', 'type' => 'default', 'created_at' => '2022-06-09 00:32:42', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '6', 'group_id' => '1', 'name' => '{"en":"Invoice Center"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => null, 'url' => '/home', 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '17', 'rgt' => '18', 'type' => 'default', 'created_at' => '2022-06-09 00:32:42', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '7', 'group_id' => '1', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '25', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '19', 'rgt' => '20', 'type' => 'default', 'created_at' => '2022-06-09 00:32:42', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '8', 'group_id' => '1', 'name' => '{"en":"Lists"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '23', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '21', 'rgt' => '22', 'type' => 'default', 'created_at' => '2022-06-09 00:32:42', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '9', 'group_id' => '1', 'name' => '{"en":"My Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '21', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '3', 'level' => null, 'depth' => '2', 'lft' => '23', 'rgt' => '24', 'type' => 'default', 'created_at' => '2022-06-09 00:32:42', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '10', 'group_id' => '2', 'name' => '{"en":"Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '20', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'type' => 'default', 'created_at' => '2022-06-11 02:45:24', 'updated_at' => '2022-06-11 02:45:24'],
            ['id' => '11', 'group_id' => '2', 'name' => '{"en":"Home"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-06-10 21:38:51', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '12', 'group_id' => '2', 'name' => '{"en":"Mega menu"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'type' => 'mega-menu', 'created_at' => '2022-06-10 21:43:28', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '13', 'group_id' => '2', 'name' => '{"en":"Products"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '15', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'type' => 'default', 'created_at' => '2022-06-11 00:34:17', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '14', 'group_id' => '2', 'name' => '{"en":"Account"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '8', 'rgt' => '17', 'type' => 'default', 'created_at' => '2022-06-11 00:35:29', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '15', 'group_id' => '2', 'name' => '{"en":"Quick Order"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '13', 'level' => null, 'depth' => '2', 'lft' => '15', 'rgt' => '16', 'type' => 'default', 'created_at' => '2022-06-11 00:36:05', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '16', 'group_id' => '2', 'name' => '{"en":"Account Summary"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '13', 'level' => null, 'depth' => '2', 'lft' => '9', 'rgt' => '10', 'type' => 'default', 'created_at' => '2022-06-11 00:36:23', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '17', 'group_id' => '2', 'name' => '{"en":"Invoice Center"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '13', 'level' => null, 'depth' => '2', 'lft' => '11', 'rgt' => '12', 'type' => 'default', 'created_at' => '2022-06-11 00:36:35', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '18', 'group_id' => '2', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => '13', 'level' => null, 'depth' => '2', 'lft' => '13', 'rgt' => '14', 'type' => 'default', 'created_at' => '2022-06-11 00:36:50', 'updated_at' => '2022-06-11 00:37:42'],
            ['id' => '19', 'group_id' => '3', 'name' => '{"en":"My Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '21', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-06-15 02:52:25', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '20', 'group_id' => '3', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '25', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'type' => 'default', 'created_at' => '2022-06-15 02:56:59', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '21', 'group_id' => '3', 'name' => '{"en":"Addresses"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '30', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '13', 'type' => 'default', 'created_at' => '2022-06-15 02:57:07', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '22', 'group_id' => '2', 'name' => '{"en":"List"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '22', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'type' => 'default', 'created_at' => '2022-06-11 02:45:24', 'updated_at' => '2022-06-11 02:45:24'],
            ['id' => '23', 'group_id' => '3', 'name' => '{"en":"Quotations"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '28', 'url' => null, 'visibility_for' => '{"authenticated": false,"admin": false,"approver": false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '8', 'rgt' => '9', 'type' => 'default', 'created_at' => '2022-06-15 02:56:59', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '24', 'group_id' => '3', 'name' => '{"en":"Contacts"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '26', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":true,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'type' => 'default', 'created_at' => '2022-06-27 22:30:56', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '25', 'group_id' => '1', 'name' => '{"en":"Store"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'type' => 'mega-menu', 'created_at' => '2022-06-28 23:38:03', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '26', 'group_id' => '3', 'name' => '{"en":"Lists"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '23', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '10', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-06-29 00:44:18', 'updated_at' => '2022-06-29 00:49:14'],
            ['id' => '28', 'group_id' => '1', 'name' => '{"en":"FAQ"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '16', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '8', 'rgt' => '9', 'type' => 'default', 'created_at' => '2022-06-29 05:42:34', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '29', 'group_id' => '3', 'name' => '{"en":"Dashboard"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '33', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'type' => 'default', 'created_at' => '2022-07-08 01:59:08', 'updated_at' => '2022-07-08 01:59:08'],
            ['id' => '30', 'group_id' => '4', 'name' => '{"en":"Home"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '14', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-07-29 22:15:30', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '32', 'group_id' => '4', 'name' => '{"en":"Shop"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '15', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-07-29 22:19:30', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '34', 'group_id' => '4', 'name' => '{"en":"Account"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '33', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '21', 'type' => 'default', 'created_at' => '2022-07-29 22:21:08', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '36', 'group_id' => '4', 'name' => '{"en":"Shop Categories"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '1', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '5', 'rgt' => '6', 'type' => 'default', 'created_at' => '2022-07-29 22:24:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '37', 'group_id' => '4', 'name' => '{"en":"Single Product"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '5', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '7', 'rgt' => '8', 'type' => 'default', 'created_at' => '2022-07-29 22:24:59', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '38', 'group_id' => '4', 'name' => '{"en":"Cart"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '20', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '9', 'rgt' => '10', 'type' => 'default', 'created_at' => '2022-07-29 22:25:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '39', 'group_id' => '4', 'name' => '{"en":"Quick Order"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '17', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '13', 'rgt' => '14', 'type' => 'default', 'created_at' => '2022-07-29 22:31:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '40', 'group_id' => '4', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '25', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '15', 'rgt' => '16', 'type' => 'default', 'created_at' => '2022-07-29 22:32:07', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '41', 'group_id' => '4', 'name' => '{"en":"Customer List"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '23', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '17', 'rgt' => '18', 'type' => 'default', 'created_at' => '2022-07-29 22:33:38', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '42', 'group_id' => '4', 'name' => '{"en":"My Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '33', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '19', 'rgt' => '20', 'type' => 'default', 'created_at' => '2022-07-29 22:34:16', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '43', 'group_id' => '4', 'name' => '{"en":"Login"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '18', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":true}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '22', 'rgt' => '23', 'type' => 'default', 'created_at' => '2022-08-02 20:51:55', 'updated_at' => '2022-08-02 20:52:40'],
            ['id' => '44', 'group_id' => '4', 'name' => '{"en":"Registration"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '19', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":true}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '24', 'rgt' => '25', 'type' => 'default', 'created_at' => '2022-08-02 20:52:21', 'updated_at' => '2022-08-02 20:52:40'],
            ['id' => '45', 'group_id' => '3', 'name' => '{"en":"Messages"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '34', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'type' => 'default', 'created_at' => '2022-08-03 23:30:06', 'updated_at' => '2022-08-03 23:30:06'],
            ['id' => '46', 'group_id' => '1', 'name' => '{"en":"About Us"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '35', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '10', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-08-24 04:06:30', 'updated_at' => '2022-08-24 04:06:57'],
            ['id' => '56', 'group_id' => '5', 'name' => '{"en":"About Us"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '35', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '13', 'type' => 'default', 'created_at' => '2022-08-24 04:06:30', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '57', 'group_id' => '5', 'name' => '{"en":"Store"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '14', 'rgt' => '15', 'type' => 'mega-menu', 'created_at' => '2022-06-28 23:38:03', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '59', 'group_id' => '6', 'name' => '{"en":"Home"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '35', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-07-29 22:15:30', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '60', 'group_id' => '6', 'name' => '{"en":"Shop"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '36', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-07-29 22:19:30', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '61', 'group_id' => '6', 'name' => '{"en":"Account"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '75', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '21', 'type' => 'default', 'created_at' => '2022-07-29 22:21:08', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '62', 'group_id' => '6', 'name' => '{"en":"Shop Categories"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '71', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '5', 'rgt' => '6', 'type' => 'default', 'created_at' => '2022-07-29 22:24:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '63', 'group_id' => '6', 'name' => '{"en":"Single Product"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '67', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '7', 'rgt' => '8', 'type' => 'default', 'created_at' => '2022-07-29 22:24:59', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '64', 'group_id' => '6', 'name' => '{"en":"Cart"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '58', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '32', 'level' => null, 'depth' => '2', 'lft' => '9', 'rgt' => '10', 'type' => 'default', 'created_at' => '2022-07-29 22:25:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '65', 'group_id' => '6', 'name' => '{"en":"Quick Order"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '61', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '13', 'rgt' => '14', 'type' => 'default', 'created_at' => '2022-07-29 22:31:33', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '66', 'group_id' => '6', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '53', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '15', 'rgt' => '16', 'type' => 'default', 'created_at' => '2022-07-29 22:32:07', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '67', 'group_id' => '6', 'name' => '{"en":"Customer List"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '55', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '17', 'rgt' => '18', 'type' => 'default', 'created_at' => '2022-07-29 22:33:38', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '68', 'group_id' => '6', 'name' => '{"en":"My Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '57', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => '34', 'level' => null, 'depth' => '2', 'lft' => '19', 'rgt' => '20', 'type' => 'default', 'created_at' => '2022-07-29 22:34:16', 'updated_at' => '2022-07-29 22:38:56'],
            ['id' => '69', 'group_id' => '6', 'name' => '{"en":"Login"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '60', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":true}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '22', 'rgt' => '23', 'type' => 'default', 'created_at' => '2022-08-02 20:51:55', 'updated_at' => '2022-08-02 20:52:40'],
            ['id' => '70', 'group_id' => '6', 'name' => '{"en":"Registration"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '59', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":true}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '24', 'rgt' => '25', 'type' => 'default', 'created_at' => '2022-08-02 20:52:21', 'updated_at' => '2022-08-02 20:52:40'],
            ['id' => '71', 'group_id' => '5', 'name' => '{"en":"Home Products"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'mega-menu', 'created_at' => '2022-09-13 17:46:55', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '72', 'group_id' => '5', 'name' => '{"en":"Car Products"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'type' => 'mega-menu', 'created_at' => '2022-09-14 14:22:57', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '73', 'group_id' => '5', 'name' => '{"en":"Security Products"}', 'class' => null, 'style' => null, 'url_type' => 'external', 'page_id' => null, 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'type' => 'mega-menu', 'created_at' => '2022-09-14 14:23:16', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '74', 'group_id' => '7', 'name' => '{"en":"My Profile"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '57', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'type' => 'default', 'created_at' => '2022-09-21 17:46:57', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '75', 'group_id' => '7', 'name' => '{"en":"Orders"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '53', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '8', 'rgt' => '9', 'type' => 'default', 'created_at' => '2022-09-21 17:47:25', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '76', 'group_id' => '7', 'name' => '{"en":"Addresses"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '48', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":true,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '18', 'rgt' => '19', 'type' => 'default', 'created_at' => '2022-09-21 17:48:05', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '77', 'group_id' => '7', 'name' => '{"en":"Quotations"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '50', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '12', 'rgt' => '13', 'type' => 'default', 'created_at' => '2022-09-21 17:48:32', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '78', 'group_id' => '7', 'name' => '{"en":"Contacts"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '52', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":true,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '16', 'rgt' => '17', 'type' => 'default', 'created_at' => '2022-09-21 17:48:56', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '79', 'group_id' => '7', 'name' => '{"en":"Lists"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '55', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '14', 'rgt' => '15', 'type' => 'default', 'created_at' => '2022-09-21 17:49:19', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '80', 'group_id' => '7', 'name' => '{"en":"Dashboard"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '45', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'type' => 'default', 'created_at' => '2022-09-21 17:49:47', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '81', 'group_id' => '7', 'name' => '{"en":"Messages"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '44', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '20', 'rgt' => '21', 'type' => 'default', 'created_at' => '2022-09-21 17:50:09', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '82', 'group_id' => '7', 'name' => '{"en":"Login"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '60', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '22', 'rgt' => '23', 'type' => 'default', 'created_at' => '2022-09-23 20:14:10', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '83', 'group_id' => '7', 'name' => '{"en":"Register"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '59', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '24', 'rgt' => '25', 'type' => 'default', 'created_at' => '2022-09-23 20:14:24', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '84', 'group_id' => '5', 'name' => '{"en":"Shop by Brand"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '72', 'url' => null, 'visibility_for' => '{"authenticated":false,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '10', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-09-30 14:53:40', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '85', 'group_id' => '5', 'name' => '{"en":"Quick Order"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '61', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '8', 'rgt' => '9', 'type' => 'default', 'created_at' => '2022-09-30 14:54:46', 'updated_at' => '2022-11-29 01:07:24'],
            ['id' => '87', 'group_id' => '7', 'name' => '{"en":"Account Summary"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '75', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'type' => 'default', 'created_at' => '2022-11-21 21:35:10', 'updated_at' => '2022-11-22 20:09:09'],
            ['id' => '88', 'group_id' => '7', 'name' => '{"en":"Invoices"}', 'class' => null, 'style' => null, 'url_type' => 'page', 'page_id' => '76', 'url' => null, 'visibility_for' => '{"authenticated":true,"admin":false,"approver":false,"guest":false}', 'parent_id' => null, 'level' => null, 'depth' => '1', 'lft' => '10', 'rgt' => '11', 'type' => 'default', 'created_at' => '2022-11-22 20:08:34', 'updated_at' => '2022-11-22 20:09:09'],
        ];

        $mega_menus = [
            ['id' => '1', 'name' => 'Featured', 'menu_column_size' => '6', 'links' => null, 'type' => 'merchandising-zones', 'menu_id' => '10', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => '2', 'number_of_merchandising_products' => '3', 'number_of_column_merchandising_zone' => '3', 'merchandising_attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":false}', 'parent_id' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'created_at' => '2022-06-10 20:46:34', 'updated_at' => '2022-06-10 20:52:57'],
            ['id' => '2', 'name' => 'Categories', 'menu_column_size' => '4', 'links' => null, 'type' => 'category', 'menu_id' => '10', 'number_of_categories' => '10', 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'created_at' => '2022-06-10 20:51:48', 'updated_at' => '2022-06-10 20:52:34'],
            ['id' => '3', 'name' => 'Categories', 'menu_column_size' => '2', 'links' => null, 'type' => 'category', 'menu_id' => '25', 'number_of_categories' => '10', 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'created_at' => '2022-06-28 17:41:30', 'updated_at' => '2022-08-23 15:19:10'],
            ['id' => '4', 'name' => 'Best Sellers', 'menu_column_size' => '4', 'links' => null, 'type' => 'merchandising-zones', 'menu_id' => '25', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => '1', 'number_of_merchandising_products' => '4', 'number_of_column_merchandising_zone' => '3', 'merchandising_attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":false}', 'parent_id' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'created_at' => '2022-06-28 17:42:27', 'updated_at' => '2022-08-23 15:19:10'],
            ['id' => '5', 'name' => 'Our Choice', 'menu_column_size' => '2', 'links' => null, 'type' => 'product', 'menu_id' => '25', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'created_at' => '2022-08-23 15:18:59', 'updated_at' => '2022-08-23 15:21:19'],

            ['id' => '6', 'name' => 'Featured', 'menu_column_size' => '6', 'links' => null, 'type' => 'merchandising-zones', 'menu_id' => '55', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => '2', 'number_of_merchandising_products' => '3', 'number_of_column_merchandising_zone' => '3', 'merchandising_attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":false}', 'parent_id' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'created_at' => '2022-06-10 20:46:34', 'updated_at' => '2022-06-10 20:52:57'],
            ['id' => '7', 'name' => 'Categories', 'menu_column_size' => '4', 'links' => null, 'type' => 'category', 'menu_id' => '55', 'number_of_categories' => '10', 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => null, 'lft' => null, 'rgt' => null, 'created_at' => '2022-06-10 20:51:48', 'updated_at' => '2022-06-10 20:52:34'],
            ['id' => '8', 'name' => 'Categories', 'menu_column_size' => '2', 'links' => null, 'type' => 'category', 'menu_id' => '57', 'number_of_categories' => '10', 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => '1', 'lft' => '2', 'rgt' => '3', 'created_at' => '2022-06-28 17:41:30', 'updated_at' => '2022-08-23 15:19:10'],
            ['id' => '9', 'name' => 'Best Sellers', 'menu_column_size' => '4', 'links' => null, 'type' => 'merchandising-zones', 'menu_id' => '57', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => '1', 'number_of_merchandising_products' => '4', 'number_of_column_merchandising_zone' => '3', 'merchandising_attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":false}', 'parent_id' => null, 'depth' => '1', 'lft' => '4', 'rgt' => '5', 'created_at' => '2022-06-28 17:42:27', 'updated_at' => '2022-08-23 15:19:10'],
            ['id' => '10', 'name' => 'Our Choice', 'menu_column_size' => '2', 'links' => null, 'type' => 'product', 'menu_id' => '57', 'number_of_categories' => null, 'html_content' => null, 'merchandising_zone_id' => null, 'number_of_merchandising_products' => null, 'number_of_column_merchandising_zone' => null, 'merchandising_attribute_access' => null, 'parent_id' => null, 'depth' => '1', 'lft' => '6', 'rgt' => '7', 'created_at' => '2022-08-23 15:18:59', 'updated_at' => '2022-08-23 15:21:19'],
        ];

        $mega_menu_products = [
            ['id' => '5', 'mega_menu_id' => '5', 'product_id' => '30274', 'product_column_size' => '12', 'attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":true}', 'created_at' => '2022-08-23 15:23:23', 'updated_at' => '2022-08-23 15:23:23'],
            ['id' => '6', 'mega_menu_id' => '10', 'product_id' => '30274', 'product_column_size' => '12', 'attribute_access' => '{"name":true,"image":true,"price":true,"short_desc":true}', 'created_at' => '2022-08-23 15:23:23', 'updated_at' => '2022-08-23 15:23:23'],
        ];

        MenuGroup::insert($menu_groups);
        Menu::insert($menus);
        MegaMenu::insert($mega_menus);
        MegaMenuProduct::insert($mega_menu_products);
        Schema::enableForeignKeyConstraints();
    }
}
