name: Send release notes to Support

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send release data to server
        run: |
          curl -X POST https://support.amplify-b2b.com/api/changelog \
          -H "Content-Type: application/json" \
          -d '{
            "tag_name": "${{ github.event.release.tag_name }}",
            "name": "${{ github.event.release.name }}",
            "body": ${{ toJson(github.event.release.body) }},
            "html_url": "${{ github.event.release.html_url }}",
            "created_at": "${{ github.event.release.created_at }}",
            "published_at": "${{ github.event.release.published_at }}",
            "author": "${{ github.event.release.author.login }}",
            "repo": "${{ github.repository }}"
          }'