name: Send release notes to Support

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send release data to server
        run: |
          echo '{"repo": "${{ github.repository }}", "release": ${{ toJson(github.event.release) }} }' > payload.json
          
          curl -X POST https://example.com \
            -H "Content-Type: application/json" \
            -d @payload.json
